name: Release (MyGet)

on:
  push:
    branches:
      - develop
     
env:
  CONFIGURATION: Release

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
      with: 
        fetch-depth: 0

    - name: Set .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Pack
      run: dotnet pack --configuration ${{ env.CONFIGURATION }} --output .

    - name: Push to MyGet
      run: dotnet nuget push "*.nupkg" --api-key ${{ secrets.MYGET_API_KEY }} --source ${{ secrets.MYGET_SOURCE }}
