name: Release (GitHub Packages)

on:
  push:
    branches:
      - develop
     
env:
  CONFIGURATION: Release

jobs:
  Build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with: 
        fetch-depth: 0
    - name: Pack
      run: dotnet pack -c Release -o pkgs
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: pkgs
        path: 'pkgs/*.nupkg'
  
  Publish:
    environment: 
      name: GitHub Packages
    runs-on: ubuntu-latest
    needs: Build
    
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v3
    - name: Authenticate to GitHub Packages
      run: dotnet nuget add source -u USERNAME -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text -n github 'https://nuget.pkg.github.com/reportportal/index.json'
    - name: Push
      run: dotnet nuget push **/*.nupkg -s 'github' -k ${{ secrets.GITHUB_TOKEN }} 